import { model, Schema, Model } from "mongoose";
import { IRefund } from "../types/refund";

const RefundSchema: Schema<IRefund> = new Schema(
  {
    RefundID: { type: String, require: true, trim: true },
    PaymentIntentID: { type: String, require: true },
    ChargeID: { type: String },
    reason: {
      type: String,
      enum: [
        "duplicate",
        "fraudulent",
        "requested_by_customer",
        "expired_uncaptured_charge", // generated by Stripe internally
      ],
    },
    status: {
      type: String,
      enum: ["pending", "succeeded", "failed", "canceled"],
    },
    receipt_number: { type: String },
    amount: { type: Number },
    created: { type: Number },
    OrderID: { type: String },
    Notes: { type: String },
    email: { type: String },
    description: { type: String },
  },
  {
    timestamps: true,
  }
);

const Refund: Model<IRefund> = model("Refund", RefundSchema);

export default Refund;
